name: todo_app
description: A beautiful application to manage all your To-Do's.
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  dynamic_color: ^1.6.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.5.0
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  path: ^1.8.3
  path_provider: ^2.1.0
  sembast: ^3.5.0+1
  shared_preferences: ^2.1.2
  riverpod_lint: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
